### ISSUE TITLE
Posts do not render when data is migrated from sample site

### ISSUE THREAD

**Issue by helmutgranda** [eueung/hugo-casper-two#1]
I could not figure out why, specially since Hugo docs specify the following: 

> "each new piece of content you place into a section will automatically inherit the type. Therefore a new file created at content/posts/new-post.md"

> https://gohugo.io/content-management/types/

After explicitly declaring the document type as "post" the posts started to render on the homepage. Now that I think about it this may be an issue with Hugo and not with this theme at all but I thought you should be aware.

I am running Hugo v0.32.2

**Comment by eueung** [comment]
thanks for the info @helmutgranda ..

btw, have you tried the provided exampleSite? In my case, there is no issue when you provided post as section as usual i.e. in the `content/post/` folder..

EM

**Comment by helmutgranda** [comment]
Unfortunately I am not able to provide a live site, it was mainly a test that I was doing locally. So, if no one else is having the issue you can consider the case closed.

Thanks for your contribution to the community!

**Comment by timhere** [comment]
Unfortunately I am also having this issue. If I add `type: post` to a file's front matter then the post displays on the front page post feed. Without this it doesn't appear.

I am using Hugo v0.49.
