### ISSUE TITLE
Missing layouts?

### ISSUE THREAD

**Issue by ThomasWeiss** [eueung/hugo-casper-two#2]
First, thanks a lot for porting this theme!

I can't manage to reproduce how the [demo site](https://eueung.github.io/hugo-casper-two/) renders. [Posts](https://eueung.github.io/hugo-casper-two/post/creating-a-new-theme/) and [pages](https://eueung.github.io/hugo-casper-two/about/) don't have the cover image (as in the original Casper theme) but when I try to add posts and pages to my site, they all render like the home page (with the cover image). When comparing the theme's layouts and the source of the demo site, it seems that they don't match?

**Comment by eueung** [comment]
hallo @ThomasWeiss, I'll push the new version in the next hours ..

**Comment by thecodeboy** [comment]
@ThomasWeiss @eueung Has this issue been resolved? Asking because I'd like to use this theme for my blog.

**Comment by eueung** [comment]
@thecodeboy , page/post templates are active ... just check the demo site (or just `hugo server`) with the exampleSite.
