### ISSUE TITLE
Can we add a search bar? 

### ISSUE THREAD

**Issue by SahilMahadwar** [eueung/hugo-casper-two#24]

**Comment by kalib** [comment]
I don't think @eueung still checks this repo... Was checking other issues reported here as well and none of them received answers from him. :/

**Comment by dixonge** [comment]
No, @eueung is absent from pretty much the entire internet. 

Hugo has several options for search listed here: https://gohugo.io/tools/search/

I'm about to try this one: https://verummeum.com/hugo-advanced-features/

**Comment by SahilMahadwar** [comment]
Ohkay
