### ISSUE TITLE
Fork or take over this abandoned theme

### ISSUE THREAD

**Issue by dixonge** [eueung/hugo-casper-two#26]
There are now 4 PR's and 13 issues with zero response from @eueung who does not appear to be active on Github any more, not to mention having zero activity on this theme for 15 months.

I enjoy this theme, but would prefer the users/community be able to make fixes as needed. It would be nice if @eueung could hand this repo off to someone else. If no response, then maybe the next best thing would be to simply fork it and move on, call it 'hugo-casper-three' or something. 

I'm not enough of a coder/programmer to handle this, but hopefully someone else could? 

Thoughts?

**Comment by dixonge** [comment]
A follow-up thought - I just discovered Hugo's built-in supplement/override mechanism (just used it to change the background image parameter in readnext-random-sori.html). Between that and Theme Components this theme is probably good as-is. I'll add a link to this issue at the end of most of the existing issues as it's really the only way to get things changed at this point. 

Unless someone else wants to do the whole fork thing :)

**Comment by somada141** [comment]
Haha just suggested that in #25. @eueung do you think you could add a couple maintainers to this so that we don't have to fork it thus confusing the community as to which version is the currently maintained?

**Comment by dixonge** [comment]
I don't think it would confuse any one if we renamed it (hugo-casper-three?) but I don't feel confident enough in Hugo *or* in git to maintain a theme repo. So until someone else does that, I'll just copy files around.

Although, now that I think of it, since this theme is, in fact, frozen in time for probably forever, forking a copy for myself wouldn't be out of the question. Damn. I need to think about this.

**Comment by dixonge** [comment]
Note: In case you haven't looked, there are already 86 forks of this theme repo. I even found one that adds Indieweb capabilities, so I will probably just move my own site to that one. 

https://github.com/jcfischer/hugo-chaschper

**Comment by somada141** [comment]
@dixonge given that the repo owner seems to be MIA using or creating a fork seems to be the way to go. I'll just close this ticket. Thanks for your help!
