### ISSUE TITLE
Home page issue in HUGO V.0.58.1

### ISSUE THREAD

**Issue by veeravignesh1** [eueung/hugo-casper-two#31]
Thanks for a awesome template..

Home page rendering into post folder... So am using a downgraded version of Hugo V.0.57
[Hugo support](https://discourse.gohugo.io/t/hugo-casper-two-theme-home-page-redirect-issue/20817/2?u=veeravignesh1) suggested that we need to use .Site.RegularPages variable to overcome the same..

Can author support in fixing the same??

**Comment by ozippy** [comment]
I have the same issue.

**Comment by dixonge** [comment]
The author of this theme has been inactive on Github for around two years. You should probably not expect any changes.

**Comment by veeravignesh1** [comment]
Can someone help us fixing the issue by creating a fork off of this project??

**Comment by ansin218** [comment]
I have been using this theme for my site and I encountered a similar problem. I have tried to fix this here: https://github.com/eueung/hugo-casper-two/pull/33/commits/3805e9ef2d509d610d0153bccebdfa2d025aa25b

It was my bad that I tried to fix issue 25 in master branch, but since it has not been accepted yet, and most likely will not be, you can find changes from issue 25 too. 

Look for the branch issue_31 where I have addressed the problem for you guys. Let me know if there was anything I missed out.

**Comment by cuotos** [comment]
I've only just got back to Hugo and found this issue. @ansin218 I've applied your fix, but noticed it then breaks the tag pages. They will all list all pages rather than just the pages containing the requested tag

**Comment by ansin218** [comment]
@cuotos I cannot quite comprehend your problem. Could you please elucidate?

Also, I am no Hugo expert but I will try my best to help you out!

**Comment by cuotos** [comment]
If you have tags on your posts then go to "site/tags/[tagname]" then all posts are displayed, not just the ones containing that tag. 

I've actually moved to using a different theme now, but its where your using .Sites.RegularPages, this will always list all pages, even on a list page that is designed to only show a subset, like the tags example above.

**Comment by y26805** [comment]
Thanks for the commit @ansin218! I had the same issue as @cuotos.

Did my own dirty fix here (https://github.com/y26805/hugo-casper-two/commit/8cd7185fe731aea79590d8d699aa8ba4789066d4)
by separating `post-list-home` from `post-list`.

to use this fix, one would have to add a param to config file
```
[params]
  mainSections = ["post"]
```

as creating a mainSection is [recommended by Hugo](https://gohugo.io/functions/where/#mainsections)

**Comment by veeravignesh1** [comment]
Author not active.
Security concern.. Better not to use the theme
